GET http://localhost:3000/posts/63e4dac587da94b5ed3ec0cf

###
GET http://localhost:3000/posts


###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2U0ZGFjNTg3ZGE5NGI1ZWQzZWMwY2YiLCJpYXQiOjE2NzYwMjU3MzQsImV4cCI6MTY3NjExMjEzNH0.EqNAgD3ZLsXvxvSh-P8LMeY5gBz2xiYGYxU45j9rYYo

{
    "img": "https://ti.postimg.cc/wjk4cgx7/hags.jpg",
    "postText": "hey , see my newh wallpaper",
    "fullname": "Alex Sexwale"

  
}

###
DELETE http://localhost:8999/posts/62275aca5d5afe9a493aa4cd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI3M2U4YWFhMTlhNTE4NzdjMjllZjIiLCJpYXQiOjE2NDY5MDQyNTQsImV4cCI6MTY0Njk5MDY1NH0.dovA2dDZZYcaK-aNZDaE46ndgjGetcp17Di-5IF0R38
###
PATCH http://localhost:8999/posts/622f3100f90c550e3ac82aaf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjI3M2U4YWFhMTlhNTE4NzdjMjllZjIiLCJpYXQiOjE2NDc5MzU3MTIsImV4cCI6MTY0ODAyMjExMn0.uGGt4hfbuzHR8p_mtOC_sbE27IdXDVtTejr7E7MY30E
Content-Type: application/json

{
    "postText":"new post"
}